enum AddPrinterResult {
  BAD_URL = "BAD_URL",
  WORKFLOW_UNSUPPORTED = "WORKFLOW_UNSUPPORTED",
  API_KEY_REQUEST_TIMED_OUT = "API_KEY_REQUEST_TIMED_OUT",
  API_KEY_REQUEST_DENIED = "API_KEY_REQUEST_DENIED",
  SUCCESS = "SUCCESS",
}

export default AddPrinterResult;
